# Config file for Bugs Life mod for Majora's Mask: Recompiled

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
id = "mm_iron_goron"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Iron Goron"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description = """
This Mod allows the use of Goron underwater. You can also punch trees to shake them and 
break the boards in front of the pirates fortress."""

# A short description that will show up in this mod's entry in the mod list.
short_description = "Go Underwater As Goron."

# Authors of this mod.
authors = [ "PixelShake92" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp that this mod can run on.
minimum_recomp_version = "1.2.2"

# Dependency mods.
dependencies = []

# Optional dependency mods.
optional_dependencies = []

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = []

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_iron_goron"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png" ]
